# Generated by Django 5.1.1 on 2024-09-15 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feishu_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BindInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feishu_auth.userinfo",
                    ),
                ),
            ],
        ),
    ]
