# Generated by Django 5.1.1 on 2024-09-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bind", "0001_initial"),
        ("feishu_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bindinfo",
            name="device_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="bindinfo",
            unique_together={("user", "device_id")},
        ),
    ]
