# Generated by Django 5.1.1 on 2024-09-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bind", "0002_bindinfo_device_id_alter_bindinfo_unique_together"),
        ("feishu_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bindinfo",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bindinfo",
            name="logged_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="bindinfo",
            unique_together={("user", "device_id", "logged_in")},
        ),
    ]
