# Generated by Django 5.1.1 on 2024-09-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                ("en_name", models.CharField(max_length=255, verbose_name="英文名称")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("avatar_big", models.URLField(verbose_name="头像大")),
                ("avatar_middle", models.URLField(verbose_name="头像中")),
                ("avatar_thumb", models.URLField(verbose_name="头像小")),
                ("avatar_url", models.URLField(verbose_name="头像url")),
                ("open_id", models.CharField(max_length=255, verbose_name="应用ID")),
                (
                    "tenant_key",
                    models.CharField(max_length=255, verbose_name="租户key"),
                ),
                ("union_id", models.CharField(max_length=255, verbose_name="联合ID")),
            ],
        ),
    ]
